# Generated by Django 5.1.1 on 2025-03-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0002_class_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='canonical_tag',
            field=models.CharField(blank=True, help_text='Canonical for SEO and social sharing', max_length=2555, null=True),
        ),
    ]
