# Generated by Django 5.1.1 on 2024-10-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0005_course_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Requirements',
            new_name='Prerequisites',
        ),
    ]
