# Generated by Django 5.1.1 on 2024-10-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0006_rename_requirements_course_prerequisites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Lessons',
            new_name='lessons',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Prerequisites',
            new_name='prerequisites',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
