# Generated by Django 5.1.1 on 2024-10-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0007_rename_lessons_course_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='time_to_call',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
