# Generated by Django 5.1.1 on 2024-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0008_leads_time_to_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='time_to_call',
            field=models.DateTimeField(),
        ),
    ]
