# Generated by Django 5.1.1 on 2024-10-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0009_alter_leads_time_to_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.CharField(max_length=1000),
        ),
    ]
