# Generated by Django 5.1.1 on 2024-10-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0010_alter_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description for SEO and social sharing', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title for SEO and social sharing', max_length=2555, null=True),
        ),
    ]
