# Generated by Django 5.1.1 on 2024-10-23 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0011_course_meta_description_course_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='course_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1500),
            preserve_default=False,
        ),
    ]
