# Generated by Django 5.1.1 on 2024-11-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0012_leads_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
