# Generated by Django 5.1.1 on 2024-11-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0014_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
