# Generated by Django 5.1.1 on 2024-12-12 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0015_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.CharField(default=django.utils.timezone.now, max_length=500000),
            preserve_default=False,
        ),
    ]
