# Generated by Django 5.1.1 on 2024-12-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0016_course_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=models.TextField(max_length=500000),
        ),
    ]
