# Generated by Django 5.1.1 on 2025-01-13 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0017_alter_course_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='buy_button_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=344),
            preserve_default=False,
        ),
    ]
