# Generated by Django 5.1.1 on 2025-01-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0018_course_buy_button_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
    ]
