# Generated by Django 5.1.1 on 2025-01-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0019_courseregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
