# Generated by Django 5.1.1 on 2025-01-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0021_course_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
