# Generated by Django 5.1.1 on 2025-02-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0022_blog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='buy_button_id',
            field=models.CharField(blank=True, max_length=344, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=models.TextField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
