# Generated by Django 5.1.1 on 2025-02-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0023_alter_course_buy_button_id_alter_course_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('skill_set', models.TextField()),
            ],
        ),
    ]
