# Generated by Django 5.1.1 on 2025-02-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0027_alter_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='study_material',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/'),
        ),
    ]
