# Generated by Django 5.1.1 on 2025-02-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0030_alter_class_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='traino.student'),
        ),
    ]
