# Generated by Django 5.1.1 on 2025-02-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0034_signup_role_alter_signup_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description for SEO and social sharing', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title for SEO and social sharing', max_length=2555, null=True),
        ),
    ]
