# Generated by Django 5.1.1 on 2025-02-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0035_blog_meta_description_blog_meta_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
