# Generated by Django 5.1.1 on 2025-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0037_alter_signup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
