# Generated by Django 5.1.1 on 2025-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0038_signup_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='is_active',
        ),
    ]
