# Generated by Django 4.2.7 on 2025-02-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0039_remove_signup_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='blog',
            name='Canonical_tag',
            field=models.CharField(blank=True, help_text='Canonical for SEO and social sharing', max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='skill_set',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='student_alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='student_alternative_phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='student_company',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='student_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='traino.signup'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_classes', to='traino.signup'),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
