# Generated by Django 5.1.1 on 2025-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0040_student_alternative_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
