# Generated by Django 5.1.1 on 2025-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0041_alter_student_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='alternative_phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
    ]
