# Generated by Django 5.1.1 on 2025-02-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0043_student_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='alternative_phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='company',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='student_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_user', to='traino.student'),
        ),
        migrations.AddField(
            model_name='signup',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='classes', to='traino.signup'),
        ),
    ]
